# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-08 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20190908_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imgs',
            field=models.ImageField(blank=True, upload_to='media/%Y%m%d'),
        ),
    ]
