# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-10 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_article_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
