# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20191011_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='imgs',
        ),
    ]
