# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 15:39
from __future__ import unicode_literals

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_remove_article_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contents',
            field=mdeditor.fields.MDTextField(default=1),
            preserve_default=False,
        ),
    ]
