# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-20 11:16
from __future__ import unicode_literals

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20191011_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='contents',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(null=True),
        ),
    ]
